import type { RequestHandler } from "@builder.io/qwik-city";
import * as v from "valibot";

const EnvSchema = v.object({
  ASSET: v.custom<Fetcher>(
    (input) => typeof input === "object" && input !== null && "fetch" in (input as object),
  ),
  TURSO_DATABASE_URL: v.pipe(v.string(), v.nonEmpty()),
  TURSO_AUTH_TOKEN: v.pipe(v.string(), v.nonEmpty()),
  AUTH_SECRET: v.pipe(v.string(), v.nonEmpty()),
  AUTH_GOOGLE_ID: v.pipe(v.string(), v.nonEmpty()),
  AUTH_GOOGLE_SECRET: v.pipe(v.string(), v.nonEmpty()),
});

type InferredEnv = v.InferOutput<typeof EnvSchema>;

// Compile-time drift guard: fails to compile if EnvSchema diverges from the
// global `Env` generated by `wrangler types`. Update EnvSchema to match.
true satisfies [InferredEnv] extends [Env]
  ? [Env] extends [InferredEnv]
    ? true
    : { error: "Env has keys missing from EnvSchema" }
  : { error: "EnvSchema has keys missing from Env" };

export const onRequest: RequestHandler = (ev) => {
  const result = v.safeParse(EnvSchema, ev.platform.env);
  if (!result.success) {
    console.error("Invalid platform.env:", result.issues);
    throw ev.error(500, "Server misconfigured");
  }
};
